spring.application.name=MovieManagementBooking
spring.datasource.url=jdbc:mysql://localhost:3306/movie
spring.datasource.username=root
spring.datasource.password=root
#means Hibernate will create/update the database table based on our Java entity.
spring.jpa.hibernate.ddl-auto=update
#shows SQL queries in the console.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#server info
server.port=8080